// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rjutdnrmvyyzmdfucurt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdXRkbnJtdnl5em1kZnVjdXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDAyMDUsImV4cCI6MjA3MjM3NjIwNX0.ijn8Lnx8Sv8OhgDE0g4e5Kt02G34_I8OWIUc1zWlbYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);